apiVersion: v1
kind: Service
metadata:
  name: cloudrate-frontend-service
spec:
  selector:
    app: cloudrate-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
