apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-backend
  template:
    metadata:
      labels:
        app: music-backend
    spec:
      containers:
        - name: music-backend
          image: gcr.io/thermal-imprint-459211-c7/music-backend:latest  
          ports:
            - containerPort: 8000
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
          volumeMounts:
            - name: firestore-key-volume
              mountPath: /var/secrets/google
              readOnly: true
      volumes:
        - name: firestore-key-volume
          secret:
            secretName: firestore-key
