apiVersion: v1
kind: Service
metadata:
  name: music-backend-service
spec:
  type: LoadBalancer
  selector:
    app: music-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
